### ISSUE TITLE
Create aviary image editor v 1.0.0

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-aviary-image-editor#1]
As a content editor, I want to edit images using aviary image editor.

Step 1.
- Install module
- Get and configure API key

Step 2.
- Go to assets, select image [Open product images]
- Click [edit image button] in toolbar 
- Should open a new bladed with 
![image](https://user-images.githubusercontent.com/7639413/28712862-11220bc8-738d-11e7-970f-ee8c87c049ea.png)
- After save we should see updated image in assets (product list)

Optional: (Rename and save original version into backup)

Links:
https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/basic-functions/blade-toolbar 

https://www.aviary.com/
https://creativesdk.adobe.com/docs/web/#/articles/gettingstarted/index.html
https://creativesdk.adobe.com/docs/web/#/articles/imageeditorui/index.html

**Comment by alex765022** [comment]
Rename and save original version into backup.
1) {originalFileName}.jpg -> {originalFileName}_backup[N].jpg
2) {changedFileName}.jpg -> {originalFileName}.jpg
3) Generate new thumbnails
