### ISSUE TITLE
Repository structure is incorrect, there shouldn't be extra folder at the root.

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-aviary-image-editor#2]

**Comment by vkrashenko** [comment]
![strctr1](https://user-images.githubusercontent.com/29459286/29326870-77bdfa7c-81ed-11e7-8b10-e2d929d3b9f2.png)
--------------------------------------------------------------------
![strctr2](https://user-images.githubusercontent.com/29459286/29326871-788b436a-81ed-11e7-8ee9-da3ef03a73a4.png)
