### ISSUE TITLE
Platform crashes after installing module

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-aviary-image-editor#7]
lease provide detailed information about your issue, thank you!

Version info: 
- Browser version: chrome
- Platform version: latest

### Expected behavior
Work as normal

### Actual behavior
Grey screen
![image](https://user-images.githubusercontent.com/1566470/43176363-296574a6-8f78-11e8-87ec-84c74545bd41.png)

### Steps to reproduce
1. Install ImageEditing module
2. Click restart

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-aviary-image-editor/releases/tag/v1.0.3

**Comment by Woland2k** [comment]
Still crashes:
![image](https://user-images.githubusercontent.com/1566470/43221711-88c5512a-9002-11e8-9ef1-233179f98865.png)

**Comment by asvishnyakov** [comment]
@Woland2k Try Ctrl+F5 or disable cache temporary

**Comment by Woland2k** [comment]
The browser cache is disabled:

![image](https://user-images.githubusercontent.com/1566470/43227275-1713fdae-9013-11e8-8ea7-0382d94c29ec.png)

**Comment by tatarincev** [comment]
@ Woland2k It was some bug in the CD system, a new version was released without the latest changes, now it fixed in 1.0.4

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-aviary-image-editor/releases/tag/v1.0.4
